### ISSUE TITLE
Ты спиздил firecrown

### ISSUE THREAD

**Issue by Kolloppoi** [Logcat78/Firecrown-site-frontend#1]
firecrown тебе не принадледит, мы пойдем судиться, тебе пизда

**Comment by Logcat78** [comment]
Пошел нахуй табуретка блять, фаеркраун мой, я вас инвалидов пинал, заставлял работать, а вы, вы, вы нахуй идите короче

**Comment by Garneg** [comment]
Фу, токсик

**Comment by Kolloppoi** [comment]
я придумал файркраун, за тобой и так скоро за казик приедут, готовь жопу и вазилин

**Comment by Logcat78** [comment]
Слышьте дитя флаттера, я твоего отчима в казино проиграл которое разрабатывает Гарнегр под видом речника

**Comment by Kolloppoi** [comment]
лучше быть детем флаттера, чем абортышем андроида, соси мой скиа

**Comment by Kolloppoi** [comment]
самого жестко наебали, а выебывался так что пиздец, сделал какую то хуйню и без работы остался, лошара

**Comment by Logcat78** [comment]
Закрой свой юай тред шлюха помойная, на флаттере пишут педики из скуратова, канак ебанный

**Comment by Kolloppoi** [comment]
малолетний забиван что то говорит, сними свою банду гасанова и потом говори, а то хуями воняет

**Comment by Logcat78** [comment]
А на счет работы, меня не наебали, это тебя наебали когда сказали что ты родной сын, я сам отказался от этой хуйни

**Comment by Kolloppoi** [comment]
да да попизди, джинсы не забудь подтянуть когда в колледж будешь заходить, а то корутина залетит

**Comment by Logcat78** [comment]
Слышь, заводи свой байк да котись от сюда в скуратов кофе пить, я реальный vamp

**Comment by Kolloppoi** [comment]
лучше в скуратове кофе пить, хоть я это и не делаю, чем ходить как маленький забиванчик с джинсами ниже жопы и в кофте с аниме

**Comment by Logcat78** [comment]
Да ты анимешник ебанный, раньше хоть дрочил на аниме тяночек, щас дрочишь на Ульяну

**Comment by Kolloppoi** [comment]
и че с того, я теперь гигачад, а ты попущ

**Comment by Logcat78** [comment]
Да але какой ты гигачад, ты теперь нефор ебанный, иди антифрод для Вани пиши, будете прада покупать

**Comment by Kolloppoi** [comment]
мне псеводокодер что то говорит за антифроды

**Comment by Logcat78** [comment]
Это Ванек твой мне писал что бы я ему помог, потому что ты кодер хауди хо ничего не можешь

**Comment by Kolloppoi** [comment]
он всем это писал, не переживай, он тебя специально не выбирал, а про хауди хо лучше вообще молчал, программист мамкин

**Comment by Logcat78** [comment]
Сын гоши дударя закрой свой мерзкий рот, мне офферы каждую неделю прилетают пока ты в скуратове пьешь латте

**Comment by Garneg** [comment]
Как сделать приложение для рекламы казика? САМЫЙ АУ#### СПОСОБ!

**Comment by Kolloppoi** [comment]
какие офферы, снова казик решил замутить?Мне тебя жаль что у тебя такой триггер на кофе, видимо так и остался в 2к17 со своим нефорским шмотом и знаниями в программировании на уровне табуретки

**Comment by Logcat78** [comment]
Господи, одноклеточная хуета которая нихуя не доводит до конца, ливает со всех проектов, бросает изучение, выебывается поверхностными знаниями имеет право открывать на меня свою гадкую пасть, развивайся кодер блять, потом че то пизди.

**Comment by Kolloppoi** [comment]
ебать тебя порвало, как пет прожект поживает?

**Comment by Logcat78** [comment]
Охуенно, код успешно спизжен, скоро будет в маркете

**Comment by Kolloppoi** [comment]
надеюсь ты над ним больше не работаешь, потому что у тебя нет прав на использование

**Comment by Kolloppoi** [comment]
а ну рас так, жди еще одни чуваков,я подгоню тебе вазелин попозже

**Comment by Logcat78** [comment]
У тебя нет прав на существование

**Comment by Kolloppoi** [comment]
стасу на гитхабе не понравилось, умираем нахуй

**Comment by Logcat78** [comment]
Каких чуваков, педиков из скуратова?

**Comment by Kolloppoi** [comment]
че у тебя за зацикленность на скуратове, хочешь а не можешь?

**Comment by Garneg** [comment]
Стас, кончай со скуратовым, ты уже не вайбовый бойчик

**Comment by Kolloppoi** [comment]
ты ведь прекрасно знаешь что я туда не хожу и не общаюсь ни с кем кто туда ходит, к чем ты это высераешь?

**Comment by Logcat78** [comment]
Ахахахах, ебанный латент мне пиздит что я чего то хочу, ты себя видел в зеркало

**Comment by Kolloppoi** [comment]
о, перешел на личности, красава, еще че скажешь?

**Comment by Logcat78** [comment]
Я не к тому что ты не красивый, а наборт, что ты теперь выглядишь как педик

**Comment by Kolloppoi** [comment]
спасибо конечно, но ты ведь знаешт что я не педик, сам ведь говорил что я на ульяну дрочу, хотя ты сам постоянно шутил что ты гей без остановки

**Comment by Logcat78** [comment]
Вот именно я шутил, а ты педик

**Comment by Logcat78** [comment]
Ты заебал, че с ctf ливнул?

**Comment by Kolloppoi** [comment]
хорошо, я ебаный пидарас и ебу мужиков в жопу, вопросы?

**Comment by Logcat78** [comment]
Вопросов нет, я тоже

**Comment by Kolloppoi** [comment]
еще есть что сказать или аргументы закончились?

**Comment by Garneg** [comment]
Блять заюзали гитхаб как тиндер

**Comment by Garneg** [comment]
Вот до чего доводят санкции

**Comment by Logcat78** [comment]
Тебя Рома на ctf звал, ты ливнул, теперь он меня зовет, у меня выбора нет, там больше некого звать, соглашайся и я тебя прощу так и быть

**Comment by Kolloppoi** [comment]
мне не хватит знаний что бы участвовать в стф, да и не хочется, хочешь опозорится, валяй

**Comment by Logcat78** [comment]
Даня, пошли пп доделаем

**Comment by Garneg** [comment]
Го, приглашай в реп

**Comment by Logcat78** [comment]
Так ты круче хакерок чем я, иди участвуй

**Comment by Logcat78** [comment]
Ща открою бро реп

**Comment by Logcat78** [comment]
Покурю

**Comment by Kolloppoi** [comment]
я никогда себя не называл хакеро и таковым не являюсь, так что откажусь

**Comment by Logcat78** [comment]
Да заебал Макс, ты че рофлов не понимаешь, успокойся

**Comment by Kolloppoi** [comment]
нет, не понимаю

**Comment by Logcat78** [comment]
Успокойся, выпей чашечку кофе

**Comment by Kolloppoi** [comment]
еще скажи что ты рофлил а не по серьезу все писал, так легко прикинуться ебланом сказав что все рофл

**Comment by Kolloppoi** [comment]
тебя мама кофе что ли запрещает пить, так уже заебал с этим кофе

**Comment by Kolloppoi** [comment]
тебе кофейную клизму плохо в детсве сделали что ты теперь кофе боишься?

**Comment by Logcat78** [comment]
Да, я писал это по рофлу, ты еблан? Нет я реально считаю что ты гей и ходишь в скуратов

**Comment by Kolloppoi** [comment]
да я гей и хожу в скуратов вообще то, это пиздец

**Comment by Logcat78** [comment]
Вот ты че то щас горишь немного бро

**Comment by Kolloppoi** [comment]
да у меня жопа после кофе горит просто

**Comment by Logcat78** [comment]
Даня ответь в тг блять

**Comment by Logcat78** [comment]
Да все успокойся, кайфани, у тебя подик есть? Если есть попари

**Comment by Kolloppoi** [comment]
я уже, мне ахуенно

**Comment by Logcat78** [comment]
Ты же завязал вроде

**Comment by Kolloppoi** [comment]
бросаю по немногу, взял слабее, скоро на безникотин перейду и все

**Comment by Logcat78** [comment]
Мега неплох, а у меня мгошка еще, хочу че нибудь по мощнее взять

**Comment by Kolloppoi** [comment]
аегис бери, это база

**Comment by Logcat78** [comment]
Мы с Даней пет проджект доделывать собрались, го к нам консультантом по дизайну, это лучшее что у тебя получается

**Comment by Kolloppoi** [comment]
блять я не дизайнер если ты не заметил, у меня вполне нормально все идет с речником, так что откажусь

**Comment by Logcat78** [comment]
А это ты бекенд делаешь для речника, я думал даня го ебанул

**Comment by Kolloppoi** [comment]
я делаю приложение, даня бекэнд

**Comment by Logcat78** [comment]
На чем аппка на флаттере?

**Comment by Kolloppoi** [comment]
вплане?

**Comment by Logcat78** [comment]
Ну на чем приложение делаешь, на флаттере или натив, просто видел нативку у Дани

**Comment by Kolloppoi** [comment]
на флаттере

**Comment by Logcat78** [comment]
А пва когда?

**Comment by Kolloppoi** [comment]
уже

**Comment by Logcat78** [comment]
Это пва?

**Comment by Kolloppoi** [comment]
то что я пишу да, даня хотел сделать натив того же просто

**Comment by Kolloppoi** [comment]
![Screenshot from 2023-10-20 23-26-44](https://github.com/Logcat78/Firecrown-site-frontend/assets/142845668/83d1324a-d448-4e00-a2fd-bbca58639b2c)

**Comment by Logcat78** [comment]
Молчи дурочка

**Comment by Kolloppoi** [comment]
Правда глаза режет лохушка?

**Comment by Logcat78** [comment]
![9UlnjmBNWYQ](https://github.com/Logcat78/Firecrown-site-frontend/assets/124933877/8ca3af65-ac2e-47f2-bdad-26e0bc64473a)

**Comment by Kolloppoi** [comment]
Жаль пет прожект, создатель вообще гений, желаю ему спокойно умереть

**Comment by Logcat78** [comment]
Да хватит плакать блять, иди занимайся речником пока не ливнул снова

**Comment by Kolloppoi** [comment]
Я ливаю только с тех проектов на которых есть ты, так что расслабься, создатель говна

**Comment by Logcat78** [comment]
У тебя больше проектов и не было, тебя инвалида никто брать не хочет

**Comment by Kolloppoi** [comment]
У тебя смотрю прям отбоя от предложений нет, пиздаболина, и хорошо что не было, а то так же умирали бы как твои высеры

**Comment by Logcat78** [comment]
Напоминаю, приглашают на работу каждую неделю

**Comment by Kolloppoi** [comment]
Пхахахахаха, че ж ты тогда до сих пор хуйней страдаешь а не работаешь профессионал ты наш, колледж мешает, ахахаххаха

**Comment by Logcat78** [comment]
Да мешает, есть такое

**Comment by Logcat78** [comment]
Ты заебал меня, че ты доебался, у тебя жизни нет что ли, че ты мне срешь в ищью

**Comment by Kolloppoi** [comment]
Ты на парах то почти не появляешься, мешает он ему, отчисляйся раз не вывозишь, а то только балаболить можешь

**Comment by Kolloppoi** [comment]
Что б тебя побесить, а то это слишком весело

**Comment by Logcat78** [comment]
В смысле почти не появляюсь, это ты пропал куда то

**Comment by Kolloppoi** [comment]
Я не прихожу если только я болею, тем более я хотя бы на парах не страдаю хуйней и не ору с Максимом на всю аудиторию как умственно отсталый

**Comment by Logcat78** [comment]
Ну да не страдаешь хуйней, сидишь доки по флаттеру читаешь

**Comment by Logcat78** [comment]
Даня спаси, он преследует меня, забери его работать в дискорд

**Comment by Kolloppoi** [comment]
Конечно не страдаю, это ты постоянно на парах ржешь над очередной хуйней и ведешь себя как дегенерат с Максом на пару, я хотя бы чем то полезным занят

**Comment by Logcat78** [comment]
Ну да, мы неандертальцы с Максом, а ты о великий гомосапиенс сидишь читаешь великое чтиво однодневной технологии вместо деградации с Ваней и Егором

**Comment by Kolloppoi** [comment]
Ваня и Егор хотя бы не ведут себя как дебилы, как например Вадим и Максим, и с ними гораздо интереснее общаться, а по поводу однодневной технологии, как всегда показал свои знания и осведомленность в теме, бездарь

**Comment by Logcat78** [comment]
![kopkagifka](https://github.com/Logcat78/Firecrown-site-frontend/assets/124933877/e27ec1f9-9591-4b0d-8b7e-59940b281657)

**Comment by Kolloppoi** [comment]
Ты зачем веб камеру включил?

**Comment by Logcat78** [comment]
А там загрузилось?

**Comment by Logcat78** [comment]
Я думал гифка не работает

**Comment by Kolloppoi** [comment]
Да вроде видео с твоей веб камеры нормально грузиться, спасибо за трансляцию

**Comment by Logcat78** [comment]
![kopkagifka](https://github.com/Logcat78/Firecrown-site-frontend/assets/124933877/dac53651-8d37-4816-8804-dee93027adc6)

**Comment by Kolloppoi** [comment]
Новый стрим SRAS2009RUS

**Comment by Logcat78** [comment]
На твиче подрубил

**Comment by Kolloppoi** [comment]
Вот ты опять и спалился что ты фем бой и дрочишь на трапов

**Comment by Logcat78** [comment]
Да, но я не дрочу на канакова

**Comment by Kolloppoi** [comment]
Я дрочу, задавайте вопросы

**Comment by Kolloppoi** [comment]
С чего ты решил что я на него дрочу, я кидал с ним гифки или что, это твои сладкие мечты, признай

**Comment by Logcat78** [comment]
Я лучше удалю стрим, я не хочу 2 пермач

**Comment by Logcat78** [comment]
Зато ты хочешь спермач от канакова

**Comment by Kolloppoi** [comment]
Причем здесь канаков, у тебя какой то бзик на него, поработай с психологом

**Comment by Logcat78** [comment]
Просто ты в него превращаешься, я за тебя боюсь

**Comment by Kolloppoi** [comment]
Каким образом я в него превращаюсь, расскажешь?

**Comment by Logcat78** [comment]
Ну пьешь ванильный латте в скуратове, носишь пальто, общаешься с Ульяной, делаешь вид что на парах занят чем то важным

**Comment by Garneg** [comment]
Уничтожен

**Comment by Logcat78** [comment]
Так да

**Comment by Garneg** [comment]
<img src="https://media.tenor.com/u6WPxNl2hLsAAAAd/%D0%BA%D0%B0%D1%88%D0%B0-%D1%81%D0%B8%D0%B3%D0%BC%D0%B0.gif"/>

**Comment by Kolloppoi** [comment]
Я ношу пальто потому что мне нравится, ты сам носил пальто год назад, в скуратове я не разу не был, с Ульяной я общаюсь потому что она вокалист у нас в группе и у нас общая кампания, а на парах я работаю, а не страдаю хуйней, делаю вид что я ебать важный

**Comment by Kolloppoi** [comment]
Сам то в кого превращаешься, в Вадима блять, самому при таких условиях не смешно мне что то говорить?

**Comment by Logcat78** [comment]
Ну Канаку тоже нравится носить пальто, этот питерский вайб, ммм

**Comment by Logcat78** [comment]
Как я в него превращаюсь?

**Comment by Kolloppoi** [comment]
Ты сам пальто носил, забыл уже?

**Comment by Kolloppoi** [comment]
Ну ты балабол конечно

**Comment by Logcat78** [comment]
Так я носил пальто оппенгеймера а не пидора

**Comment by Logcat78** [comment]
У меня еще шапка была как у него

**Comment by Kolloppoi** [comment]
Какого блять опенгеймера, че ты несешь

**Comment by Garneg** [comment]
ХАХАХАХХАХАХ

**Comment by Kolloppoi** [comment]
Вадим на тебя плохо влияет

**Comment by Logcat78** [comment]
Я оппенгеймер нахуй, а ты сосешь хуи мужиков дура

**Comment by Kolloppoi** [comment]
Жаль вашу кампанию, надеюсь отчислят без лишних криков

**Comment by Garneg** [comment]
Все жду когда же вы уже признаетесь друг другу и поебетесь

**Comment by Logcat78** [comment]
Вадим кстати не моя компания

**Comment by Kolloppoi** [comment]
Я Канадову уже признался

**Comment by Logcat78** [comment]
Уууу, ууу признался канакову, мммммм

**Comment by Kolloppoi** [comment]
Да да, конечно, думай так дальше, только ему не забудь об этом сказать что б он тебе ебало снес

**Comment by Garneg** [comment]
Только не ревнуй, Стас

**Comment by Logcat78** [comment]
Да че он там снесет, он тебе девственность снесе пенисом

**Comment by Logcat78** [comment]
Я ревнивая сучка

**Comment by Kolloppoi** [comment]
По своему опыту судишь, заднюю передачу не забудь переключить

**Comment by Logcat78** [comment]
Расскажешь парню в постеле

**Comment by Kolloppoi** [comment]
У нас с твоим папой самые проникновенные беседы

**Comment by DirtyPoo** [comment]
а ну-ка угомонись сына Скуратова
всем завтра по попе надаю

**Comment by Kolloppoi** [comment]
Иди нахуй максим

**Comment by Logcat78** [comment]
Я твоего отчима так то в казино проиграл, если не помнишь

**Comment by Kolloppoi** [comment]
Стасик позвал помочь, и сразу прибежал, как мило Максим

**Comment by Logcat78** [comment]
Максиму просто пришел инвайт на прада пати

**Comment by Kolloppoi** [comment]
Окей, нового потом купишь

**Comment by DirtyPoo** [comment]
тебе когда-нибудь говорили максим, что тебя не планировали?

**Comment by DirtyPoo** [comment]
я вызываю тебя на версус батл бпм

**Comment by Kolloppoi** [comment]
Когда к тебе Максим обращались, то да, слышал говорили

**Comment by Logcat78** [comment]
Я дрочить хочу

**Comment by Kolloppoi** [comment]
На Каганова подрочи пупс

**Comment by Logcat78** [comment]
Это твоя сфера зай

**Comment by Kolloppoi** [comment]
Какой тебе версус батл, иди биты Стасу пиши и в жопу дальше ебитесь

**Comment by Logcat78** [comment]
Я дрочу на мизухару из девушки на час, как ты раньше

**Comment by DirtyPoo** [comment]
я хочу твою попку на час

**Comment by Logcat78** [comment]
Пока Ульяну не встретил

**Comment by Kolloppoi** [comment]
Пришли два Гея блять, иди поебитесь уже

**Comment by Logcat78** [comment]
Да мы уже

**Comment by Kolloppoi** [comment]
Причем здесь Ульяна вообще?

**Comment by Garneg** [comment]
Бляяяя, это ахуенно

**Comment by Logcat78** [comment]
Теперь тебя хотим выебать

**Comment by Kolloppoi** [comment]
И кстати мидзухара хуйня

**Comment by Logcat78** [comment]
Согл, она ты еще шлюха

**Comment by Kolloppoi** [comment]
Не получится, будете только вдвоем трахаться

**Comment by Kolloppoi** [comment]
Хорошо, я ей передам

**Comment by Logcat78** [comment]
Я щас еще позову человека который сегодня 12 часов стоял в очереди за пиццей с хонкай стар рейл, он тебя сожрет нахуй

**Comment by Kolloppoi** [comment]
О чем ты вообще, че за хуйню ты несешь, убожество

**Comment by Logcat78** [comment]
Кстати тебя Канак в геншине пробустил?

**Comment by DirtyPoo** [comment]
вот ты в интернете такой смелый

**Comment by Garneg** [comment]
Пиздец, надеюсь он хотя бы открыть гитхаб сможет, с такой болезнью

**Comment by Kolloppoi** [comment]
Я не играю в геншин

**Comment by DirtyPoo** [comment]
давай завтра поговорим

**Comment by Garneg** [comment]
ООООооооо

**Comment by Logcat78** [comment]
Ты кому пишешь это Макс Фед?

**Comment by DirtyPoo** [comment]
у входа в колледж 
чтобы тебя кофесоски не защитили

**Comment by Kolloppoi** [comment]
Мне не о чем с тобой разговаривать, угрозы свои себе оставь, и не подходи ко мне нахуй вообще

**Comment by Logcat78** [comment]
АХАХАХАХХАХАХАХА

**Comment by DirtyPoo** [comment]
ты просто боишься

**Comment by DirtyPoo** [comment]
я тебя с револьвера урою нахуй

**Comment by Kolloppoi** [comment]
Хорошо, как скажешь

**Comment by Logcat78** [comment]
Ты хочешь забивчик Максим, так я как раз забивной по твоим словам

**Comment by Kolloppoi** [comment]
Да я боюсь очень сильно помогите

**Comment by Kolloppoi** [comment]
Я вроде ничего не хотел, о чем ты

**Comment by DirtyPoo** [comment]
Максим смелый, пока его лицо не располагается на траектории движения моего кулака

**Comment by Logcat78** [comment]
Ну мой vipper man хочет порешать вопросы с фанатом латте, как я могу не впрячься

**Comment by Kolloppoi** [comment]
Сказать больше нечего, угрозы пошли, продолжишь дальше, будешь сидеть в отделе

**Comment by Logcat78** [comment]
Ахахаххахаххах

**Comment by Garneg** [comment]
Забить стрелку в issue на гитхабе 💀

**Comment by Logcat78** [comment]
Бля, я ролик про это сделал на ютуб, видимо будет 2 часть

**Comment by Kolloppoi** [comment]
Хорошо, буду ждать

**Comment by Logcat78** [comment]
Не парься Макс мы рофлим, но до поры до времени

**Comment by Kolloppoi** [comment]
Я уже боюсь, так что оба будете на бутылке сидеть, до поры до времени

**Comment by DirtyPoo** [comment]
![izvrachenec](https://github.com/Logcat78/Firecrown-site-frontend/assets/148719038/ca86d5b8-aae8-4f97-abf1-c03fabb346b5)
будешь так разговаривать максим только на уровне моей ширинки

**Comment by Kolloppoi** [comment]
Чел слишком худой на фото, это не ты

**Comment by Logcat78** [comment]
О, + личное оск

**Comment by DirtyPoo** [comment]
![image](https://github.com/Logcat78/Firecrown-site-frontend/assets/148719038/a078ff6c-ed45-45fc-ad5c-929436144413)

**Comment by DirtyPoo** [comment]
Я порву тебя как тузик грелку

**Comment by Kolloppoi** [comment]
Я просто констатировал факт, я не обзывал никого, так что мимо

**Comment by Kolloppoi** [comment]
Максим, ты вообще что тут забыл, тебя Стас попросил подсосать ему и ты тут же примчался?

**Comment by Kolloppoi** [comment]
Самому то не смешно?

**Comment by DirtyPoo** [comment]
Короче ты тремя пулевыми вряд ли отмажешься

**Comment by Logcat78** [comment]
Даня, а ты за кого в этом жестком бифе, за тру вампиров, или за соевого любителя латте?

**Comment by Logcat78** [comment]
Я не просил кстати, Максим сам решил зайти

**Comment by Kolloppoi** [comment]
Че сообщение про Ульяну удалил?

**Comment by DirtyPoo** [comment]
ты у меня ноги в тазике с цементом греть будешь
если попытаешься мусорнуться

**Comment by DirtyPoo** [comment]
![image](https://github.com/Logcat78/Firecrown-site-frontend/assets/148719038/f63cc55f-e49b-4148-ad84-3bb4ea3e947f)

**Comment by Kolloppoi** [comment]
Мы можем это обсудить в нормальном месте, например в дисе или ВК

**Comment by Logcat78** [comment]
Я курил, че было

**Comment by Logcat78** [comment]
Го в дс

**Comment by Kolloppoi** [comment]
Приглашай

**Comment by Kolloppoi** [comment]
Максима еще не забудь позвать

**Comment by Logcat78** [comment]
В сос тусу заходи

**Comment by Kolloppoi** [comment]
Создай группу и Даню пригласи

**Comment by Logcat78** [comment]
Даня, ты пойдешь в дс?

**Comment by Garneg** [comment]
Да

**Comment by lil1337** [comment]
что это за сборище даунов сверху

**Comment by Logcat78** [comment]
Да ебланы какие-то, забей
